test_shazam: clean worktree before git am
I see the following failures on master (as of commit 965071ee174d):

- test_shazam[shazam-git1-just-series-shazamargs1-compareargs1-shazam-git1-just-series-defaults-b4cfg1] FAILED
Error: "fatal: Dirty index: cannot apply patches (dirty: file1.txt file2.txt lipsum.txt)"

- test_shazam[shazam-git1-just-series-shazamargs2-compareargs2-shazam-git1-just-series-merged-b4cfg2] FAILED
Error: "fatal: Dirty index: cannot apply patches (dirty: file1.txt file2.txt lipsum.txt)"

Both tests fail because git am can't apply patches with a dirty index.

Specifically, the worktree is created with `git worktree add --detach --no-checkout`,
to save time checking out files to the working directory.
However, this means all files then appear as deleted in the index.

The test attempts to solve this by a combination of
"git sparse-checkout init" followed by "git checkout".
However, "git sparse-checkout init" does not actually create an empty
sparse checkout cone and additionally "git checkout" by default does not
update the index - it only updates the worktree from the index.

As a result, when "git am" tries to apply patches, it fails with "Dirty
index: cannot apply patches" because the index contains staged changes
(the "deleted" entries).

To fix, replace "git sparse-checkout init" with "git sparse-checkout
set"  - with no patterns, this actually creates an empty sparse checkout -
followed by "git checkout -f" to update the index to match HEAD,
clearing the staged deletions.

Signed-off-by: Michael S. Tsirkin <mst@redhat.com>