fix Generator annotation type
Generator type arguments in Python 3.12 are not set to None by default.
Set them explicitly to avoid error below in distros with Python 3.12.

Error:
./b4.sh -h
Traceback (most recent call last):
  File "/media/tarkir/dagomez/src/mricon/b4/src/b4/command.py", line 10, in <module>
    import b4
  File "/media/tarkir/dagomez/src/mricon/b4/src/b4/__init__.py", line 2784, in <module>
    def git_temp_worktree(gitdir: Optional[str] = None, commitish: Optional[str] = None) -> Generator[str]:
                                                                                            ~~~~~~~~~^^^^^
  File "/usr/lib/python3.12/typing.py", line 398, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/typing.py", line 1482, in __getitem__
    _check_generic(self, params, self._nparams)
  File "/usr/lib/python3.12/typing.py", line 304, in _check_generic
    raise TypeError(f"Too {'many' if alen > elen else 'few'} arguments for {cls};"
TypeError: Too few arguments for typing.Generator; actual 1, expected 3

Fixes 2801becd386bf9b3c8947421f3ef20442def2a58 ("Correctly type annotate
generators").

Signed-off-by: Daniel Gomez <da.gomez@samsung.com>
Link: https://patch.msgid.link/20250123-fix-generator-type-v1-1-1e76428f9872@samsung.com
Signed-off-by: Konstantin Ryabitsev <konstantin@linuxfoundation.org>